### ISSUE TITLE
Web login

### ISSUE THREAD

**Issue by Cadu12** [globalreachtech/tinyradius-netty#128]
I don't see any document about it Web Login. It appends web login hotspot when connects wi-fi if we are at mall?

**Comment by horaceli** [comment]
Thats outside the scope of this project. This lib is just for marshalling Radius packets and some basic implementions for a netty-based server to listen / send said packets.

If you wanted a captive portal, you'd have to build your own server that would listen on HTTP (for the captive portal) and, based on authentication there, send a Radius response using this library. Of course you'd also have to config the routers for this flow.

**Comment by Cadu12** [comment]
I thought it looked like Radius. Sorry!

**Comment by horaceli** [comment]
No worries!

For your use case, you might want to look at [FreeRadius](https://en.wikipedia.org/wiki/FreeRADIUS) (and the corresponding Java module JRadius) and the multiple extensions that have been built for it. That's a server in itself rather than just a library.
