### ISSUE TITLE
convert the project to android app project . that will be great

### ISSUE THREAD

**Issue by adsonmanjer** [globalreachtech/tinyradius-netty#138]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by adsonmanjer** [comment]
this code is able to convert to android project and this will be the first source of this kind unfortunately i dont have a freetime to do that

**Comment by horaceli** [comment]
This is just a library at the moment and no plans to make it more than that. For Android, it's intended to be used as a library via Gradle dependency.

If theres specific Java APIs that are used that causes problems on Android, then we can open a ticket just for that.
