### ISSUE TITLE
TinyRadius Netty RadiusClient test program does not shutdown & return despite closing the NioDatagramChannel & shutting down NioEventLoopGroup

### ISSUE THREAD

**Issue by softwarebrahma** [globalreachtech/tinyradius-netty#265]
**Describe the bug**
If I try to test the [client test program](https://github.com/globalreachtech/tinyradius-netty/blob/master/src/test/java/org/tinyradius/io/TestClient.java) as-is I see that the program does not finish & return after executing the main method. When I look up for active socket use (with netstat -anpe) I see that its still connected. More details are in [this](https://stackoverflow.com/questions/76863123/tinyradius-netty-radiusclient-test-program-does-not-shutdown-return-despite-cl) SO question.

**To Reproduce**
Please see [this](https://stackoverflow.com/questions/76863123/tinyradius-netty-radiusclient-test-program-does-not-shutdown-return-despite-cl) SO question which has all the details & code.

**Expected behavior**
Program needs to finish (closing UNIX domain socket actively connected) & return after executing the main method.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser : N/A
 - Version [e.g. 22] Linux Ubuntu1_32_147 3.13.0-143-generic #192-Ubuntu SMP Tue Feb 27 10:45:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
N/A

**Comment by horaceli** [comment]
closing in favour of #62
