### ISSUE TITLE
Vendor ID not included in attribute

### ISSUE THREAD

**Issue by franck-malka** [globalreachtech/tinyradius-netty#288]
Do

List<RadiusAttribute> attributes = new ArrayList<RadiusAttribute>();
RadiusAttribute msMppeSendKeyAttr = msg.getRequest().getDictionary().createAttribute(311, 16, 
       AttributeCodecType.RFC2868_TUNNEL_PASSWORD.getId(), sndKey);
        attributes.add(msMppeSendKeyAttr);
RadiusResponse answer = RadiusResponse.create(msg.getRequest().getDictionary(), ACCESS_ACCEPT, msg.getRequest().getId(),  null, attributes);
ctx.writeAndFlush(msg.withResponse(answer));

Result

The Access_Accept response sent out doesn't include the VendorID, and the attribute is identified as VendorID -1  Login-TCP-port

What's the right way to insert the VendorID?

**Comment by horaceli** [comment]
Take a look at `VendorSpecificAttributeTest` - you need to wrap them in a `VendorSpecificAttribute` so it adds the correct byte headers and tags

**Comment by franck-malka** [comment]
Thanks
I did manage to get it done properly
