### ISSUE TITLE
Make sure TestClient / TestServer / TestProxy work

### ISSUE THREAD

**Issue by horaceli** [globalreachtech/tinyradius-netty#62]
- Make sure TestClient / TestServer / TestProxy work
- Implement them as tests instead of scripts

**Comment by softwarebrahma** [comment]
@horaceli  @sdmgrt @ctran @wuttke I just saw this after [this](https://stackoverflow.com/questions/76863123/tinyradius-netty-radiusclient-test-program-does-not-shutdown-return-despite-cl) SO question. Though I am new to Netty, I can fix & verify this....if you don't mind can you please share any pointers on what I may be missing in that SO question?

**Comment by horaceli** [comment]
@softwarebrahma could you take a look at #272 and see if the new e2e tests addresses your issue?

**Comment by horaceli** [comment]
fixed in #273
